/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "go.virtual-secrets.dev/apimachinery/apis/config/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeSecretStores implements SecretStoreInterface
type FakeSecretStores struct {
	Fake *FakeConfigV1alpha1
}

var secretstoresResource = v1alpha1.SchemeGroupVersion.WithResource("secretstores")

var secretstoresKind = v1alpha1.SchemeGroupVersion.WithKind("SecretStore")

// Get takes name of the secretStore, and returns the corresponding secretStore object, and an error if there is any.
func (c *FakeSecretStores) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.SecretStore, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(secretstoresResource, name), &v1alpha1.SecretStore{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SecretStore), err
}

// List takes label and field selectors, and returns the list of SecretStores that match those selectors.
func (c *FakeSecretStores) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.SecretStoreList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(secretstoresResource, secretstoresKind, opts), &v1alpha1.SecretStoreList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.SecretStoreList{ListMeta: obj.(*v1alpha1.SecretStoreList).ListMeta}
	for _, item := range obj.(*v1alpha1.SecretStoreList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested secretStores.
func (c *FakeSecretStores) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(secretstoresResource, opts))
}

// Create takes the representation of a secretStore and creates it.  Returns the server's representation of the secretStore, and an error, if there is any.
func (c *FakeSecretStores) Create(ctx context.Context, secretStore *v1alpha1.SecretStore, opts v1.CreateOptions) (result *v1alpha1.SecretStore, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(secretstoresResource, secretStore), &v1alpha1.SecretStore{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SecretStore), err
}

// Update takes the representation of a secretStore and updates it. Returns the server's representation of the secretStore, and an error, if there is any.
func (c *FakeSecretStores) Update(ctx context.Context, secretStore *v1alpha1.SecretStore, opts v1.UpdateOptions) (result *v1alpha1.SecretStore, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(secretstoresResource, secretStore), &v1alpha1.SecretStore{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SecretStore), err
}

// Delete takes name of the secretStore and deletes it. Returns an error if one occurs.
func (c *FakeSecretStores) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(secretstoresResource, name, opts), &v1alpha1.SecretStore{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSecretStores) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(secretstoresResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.SecretStoreList{})
	return err
}

// Patch applies the patch and returns the patched secretStore.
func (c *FakeSecretStores) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.SecretStore, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(secretstoresResource, name, pt, data, subresources...), &v1alpha1.SecretStore{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SecretStore), err
}
