/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "go.virtual-secrets.dev/apimachinery/apis/config/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeSecretSources implements SecretSourceInterface
type FakeSecretSources struct {
	Fake *FakeConfigV1alpha1
}

var secretsourcesResource = v1alpha1.SchemeGroupVersion.WithResource("secretsources")

var secretsourcesKind = v1alpha1.SchemeGroupVersion.WithKind("SecretSource")

// Get takes name of the secretSource, and returns the corresponding secretSource object, and an error if there is any.
func (c *FakeSecretSources) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.SecretSource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(secretsourcesResource, name), &v1alpha1.SecretSource{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SecretSource), err
}

// List takes label and field selectors, and returns the list of SecretSources that match those selectors.
func (c *FakeSecretSources) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.SecretSourceList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(secretsourcesResource, secretsourcesKind, opts), &v1alpha1.SecretSourceList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.SecretSourceList{ListMeta: obj.(*v1alpha1.SecretSourceList).ListMeta}
	for _, item := range obj.(*v1alpha1.SecretSourceList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested secretSources.
func (c *FakeSecretSources) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(secretsourcesResource, opts))
}

// Create takes the representation of a secretSource and creates it.  Returns the server's representation of the secretSource, and an error, if there is any.
func (c *FakeSecretSources) Create(ctx context.Context, secretSource *v1alpha1.SecretSource, opts v1.CreateOptions) (result *v1alpha1.SecretSource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(secretsourcesResource, secretSource), &v1alpha1.SecretSource{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SecretSource), err
}

// Update takes the representation of a secretSource and updates it. Returns the server's representation of the secretSource, and an error, if there is any.
func (c *FakeSecretSources) Update(ctx context.Context, secretSource *v1alpha1.SecretSource, opts v1.UpdateOptions) (result *v1alpha1.SecretSource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(secretsourcesResource, secretSource), &v1alpha1.SecretSource{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SecretSource), err
}

// Delete takes name of the secretSource and deletes it. Returns an error if one occurs.
func (c *FakeSecretSources) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(secretsourcesResource, name, opts), &v1alpha1.SecretSource{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSecretSources) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(secretsourcesResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.SecretSourceList{})
	return err
}

// Patch applies the patch and returns the patched secretSource.
func (c *FakeSecretSources) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.SecretSource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(secretsourcesResource, name, pt, data, subresources...), &v1alpha1.SecretSource{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SecretSource), err
}
