/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "go.virtual-secrets.dev/apimachinery/apis/config/v1alpha1"
	scheme "go.virtual-secrets.dev/apimachinery/client/clientset/versioned/scheme"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// SecretSourcesGetter has a method to return a SecretSourceInterface.
// A group's client should implement this interface.
type SecretSourcesGetter interface {
	SecretSources() SecretSourceInterface
}

// SecretSourceInterface has methods to work with SecretSource resources.
type SecretSourceInterface interface {
	Create(ctx context.Context, secretSource *v1alpha1.SecretSource, opts v1.CreateOptions) (*v1alpha1.SecretSource, error)
	Update(ctx context.Context, secretSource *v1alpha1.SecretSource, opts v1.UpdateOptions) (*v1alpha1.SecretSource, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.SecretSource, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.SecretSourceList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.SecretSource, err error)
	SecretSourceExpansion
}

// secretSources implements SecretSourceInterface
type secretSources struct {
	client rest.Interface
}

// newSecretSources returns a SecretSources
func newSecretSources(c *ConfigV1alpha1Client) *secretSources {
	return &secretSources{
		client: c.RESTClient(),
	}
}

// Get takes name of the secretSource, and returns the corresponding secretSource object, and an error if there is any.
func (c *secretSources) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.SecretSource, err error) {
	result = &v1alpha1.SecretSource{}
	err = c.client.Get().
		Resource("secretsources").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of SecretSources that match those selectors.
func (c *secretSources) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.SecretSourceList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.SecretSourceList{}
	err = c.client.Get().
		Resource("secretsources").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested secretSources.
func (c *secretSources) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("secretsources").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a secretSource and creates it.  Returns the server's representation of the secretSource, and an error, if there is any.
func (c *secretSources) Create(ctx context.Context, secretSource *v1alpha1.SecretSource, opts v1.CreateOptions) (result *v1alpha1.SecretSource, err error) {
	result = &v1alpha1.SecretSource{}
	err = c.client.Post().
		Resource("secretsources").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(secretSource).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a secretSource and updates it. Returns the server's representation of the secretSource, and an error, if there is any.
func (c *secretSources) Update(ctx context.Context, secretSource *v1alpha1.SecretSource, opts v1.UpdateOptions) (result *v1alpha1.SecretSource, err error) {
	result = &v1alpha1.SecretSource{}
	err = c.client.Put().
		Resource("secretsources").
		Name(secretSource.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(secretSource).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the secretSource and deletes it. Returns an error if one occurs.
func (c *secretSources) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("secretsources").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *secretSources) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("secretsources").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched secretSource.
func (c *secretSources) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.SecretSource, err error) {
	result = &v1alpha1.SecretSource{}
	err = c.client.Patch(pt).
		Resource("secretsources").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
