apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: virttual-secrets
  name: secretmounts.virtual-secrets.dev
spec:
  group: virtual-secrets.dev
  names:
    kind: SecretMount
    listKind: SecretMountList
    plural: secretmounts
    singular: secretmount
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              name:
                type: string
            required:
            - name
            type: object
          status:
            properties:
              name:
                type: string
            required:
            - name
            type: object
        type: object
    served: true
    storage: true
